import React from 'react';
import { Printer, X, FileText, ShieldAlert, Info } from 'lucide-react';
import { formatClock } from './format.js';

/**
 * Modern Minimalist Session Report Modal
 */
export default function ReportModal({ open, onClose, sim, config, startedAt }) {
  if (!open) return null;

  const runDurationSec = Math.round(sim.t);
  const nowStr = new Date().toLocaleString();

  // Events are newest-first: report only what actually happened in this run.
  const leakEvent  = sim.events.find((e) => e.severity === 'critical');
  const resetEvent = sim.events.find((e) => e.message.includes('acknowledged the alarm'));
  const resetAfterLeak = leakEvent && resetEvent && resetEvent.id > leakEvent.id;

  return (
    <div className="twin-report fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/50 backdrop-blur-xs animate-in fade-in duration-150">
      <div className="bg-white dark:bg-slate-900 rounded-2xl max-w-2xl w-full max-h-[85vh] flex flex-col shadow-xl border border-slate-200 dark:border-slate-800 overflow-hidden">
        {/* Header */}
        <div className="p-4 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between no-print">
          <div className="flex items-center gap-2">
            <FileText className="w-4 h-4 text-blue-600 dark:text-blue-400" />
            <span className="font-semibold text-sm text-slate-900 dark:text-white">
              Simulation Session Report
            </span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => window.print()}
              className="px-3 py-1 rounded-lg text-xs font-medium bg-slate-900 dark:bg-white text-white dark:text-slate-900 hover:bg-slate-800 dark:hover:bg-slate-100 transition-colors flex items-center gap-1.5 cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" /> Print
            </button>
            <button
              onClick={onClose}
              className="p-1 rounded-lg text-slate-400 hover:text-slate-600 dark:hover:text-slate-200"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto space-y-5 text-slate-800 dark:text-slate-200 text-xs print:p-0">
          <div>
            <h2 className="text-base font-bold text-slate-900 dark:text-white">
              SWAMPDS Digital Twin - Run Summary
            </h2>
            <p className="text-slate-400 mt-0.5">Timestamp: {nowStr} · Duration: {runDurationSec}s</p>
            <p className="mt-1 font-semibold text-amber-700 dark:text-amber-400">
              Simulated data - generated by a software model, not by physical hardware.
            </p>
          </div>

          {/* Key Parameters */}
          <div className="grid grid-cols-3 gap-2.5">
            <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200/60 dark:border-slate-700/60">
              <span className="text-slate-400 uppercase text-[10px] font-medium">Tolerance</span>
              <div className="text-sm font-semibold font-mono text-slate-900 dark:text-white mt-0.5">
                ±{config.tolerancePct}%
              </div>
            </div>
            <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200/60 dark:border-slate-700/60">
              <span className="text-slate-400 uppercase text-[10px] font-medium">Persistence</span>
              <div className="text-sm font-semibold font-mono text-slate-900 dark:text-white mt-0.5">
                {config.persistSec}s
              </div>
            </div>
            <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200/60 dark:border-slate-700/60">
              <span className="text-slate-400 uppercase text-[10px] font-medium">Pump Safety</span>
              <div className="text-sm font-semibold font-mono text-slate-900 dark:text-white mt-0.5">
                {sim.latched ? 'Interlocked' : 'Operational'}
              </div>
            </div>
          </div>

          {/* Sensor Telemetry Table */}
          <div className="border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden">
            <table className="w-full text-left font-mono text-[11px]">
              <thead className="bg-slate-50 dark:bg-slate-800/70 text-slate-500 font-semibold border-b border-slate-200 dark:border-slate-800">
                <tr>
                  <th className="p-2.5">Sensor</th>
                  <th className="p-2.5">Flow (L/min)</th>
                  <th className="p-2.5">Variance (Δ)</th>
                  <th className="p-2.5">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                <tr>
                  <td className="p-2.5 font-semibold">Sensor F1</td>
                  <td className="p-2.5">{sim.flows.f1.toFixed(2)}</td>
                  <td className="p-2.5">—</td>
                  <td className="p-2.5 text-emerald-600">Reference</td>
                </tr>
                <tr>
                  <td className="p-2.5 font-semibold">Sensor F2</td>
                  <td className="p-2.5">{sim.flows.f2.toFixed(2)}</td>
                  <td className="p-2.5">{sim.segments.A.diffPct.toFixed(1)}%</td>
                  <td className="p-2.5">{sim.segments.A.leak ? 'Leak' : 'OK'}</td>
                </tr>
                <tr>
                  <td className="p-2.5 font-semibold">Sensor F3</td>
                  <td className="p-2.5">{sim.flows.f3.toFixed(2)}</td>
                  <td className="p-2.5">{sim.segments.B.diffPct.toFixed(1)}%</td>
                  <td className="p-2.5">{sim.segments.B.leak ? 'Leak' : 'OK'}</td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Recent Events */}
          <div>
            <h4 className="font-semibold text-slate-600 dark:text-slate-400 mb-2">Recent Events</h4>
            <div className="max-h-40 overflow-y-auto space-y-1 font-mono text-[11px] text-slate-500">
              {sim.events.slice(0, 8).map((e) => (
                <div key={e.id} className="flex gap-2">
                  <span className="text-slate-400">{formatClock(startedAt, e.t)}</span>
                  <span className="text-slate-700 dark:text-slate-300 font-sans">{e.message}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Result: only what this run actually did */}
          <div
            className={`p-3 rounded-xl border flex items-start gap-2 text-xs ${
              leakEvent
                ? 'bg-rose-50/60 dark:bg-rose-950/20 border-rose-200/60 dark:border-rose-800/30 text-rose-800 dark:text-rose-300'
                : 'bg-slate-50 dark:bg-slate-800/50 border-slate-200/60 dark:border-slate-700/60 text-slate-600 dark:text-slate-300'
            }`}
          >
            {leakEvent
              ? <ShieldAlert className="w-4 h-4 flex-shrink-0 mt-0.5" />
              : <Info className="w-4 h-4 flex-shrink-0 mt-0.5" />}
            <div>
              <p className="font-semibold">Result</p>
              <p className="mt-0.5">
                {leakEvent
                  ? `${leakEvent.message}${resetAfterLeak ? ' The operator then reset the system.' : ''}`
                  : 'No leak was declared during this run.'}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
