import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Droplets, FlaskConical, Workflow, Lightbulb } from 'lucide-react';

import { Card, CardHeader } from '../components/Card';
import SystemStatusBanner from '../components/dashboard/SystemStatusBanner';
import FlowChart from '../components/dashboard/FlowChart';

import { useTwin } from './useTwin.js';
import { useBuzzer } from './useBuzzer.js';
import { useMediaQuery } from './useMediaQuery.js';
import { deriveOutputs } from './outputs.js';
import { SEGMENTS } from './config.js';
import { formatElapsed } from './format.js';

import PipelineSchematic from './PipelineSchematic.jsx';
import ControlPanel from './ControlPanel.jsx';
import HardwarePanel from './HardwarePanel.jsx';
import DetectionPanel from './DetectionPanel.jsx';
import EventLog from './EventLog.jsx';

const DEMO_STEPS = [
  'Wait a moment - the pump starts on its own and water flows.',
  'Drag Valve A or B open to simulate a leak.',
  'Watch the difference grow. After the persistence time the leak is confirmed and the pump is cut off.',
  'Close both valves, then press Acknowledge & Reset.',
];

/**
 * Public digital-twin simulation of the SWAMPDS pipeline.
 * Fully client-side: no Firebase, no login, no hardware.
 */
export default function TwinPage() {
  const twin = useTwin();
  const { sim, config, startedAt } = twin;

  const [soundOn, setSoundOn] = useState(true);
  const wide = useMediaQuery('(min-width: 768px)');
  const outputs = useMemo(() => deriveOutputs(sim), [sim]);
  useBuzzer(outputs.buzzer, soundOn);

  const chartData = useMemo(
    () => sim.history.map((p) => ({ time: formatElapsed(p.t), F1: p.F1, F2: p.F2, F3: p.F3 })),
    [sim.history],
  );

  useEffect(() => {
    const previous = document.title;
    document.title = 'SWAMPDS Digital Twin - Simulation';
    return () => { document.title = previous; };
  }, []);

  return (
    <div className="min-h-screen bg-slate-50 font-sans">
      {/* Header */}
      <header className="bg-[#0B1120] text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between gap-3">
          <div className="flex items-center gap-3 min-w-0">
            <Droplets className="w-7 h-7 text-blue-500 flex-shrink-0" />
            <div className="min-w-0">
              <h1 className="font-bold text-lg leading-none tracking-tight truncate">SWAMPDS Digital Twin</h1>
              <p className="text-[10px] text-slate-400 mt-1 truncate">Smart Water Management &amp; Pipeline Leak Detection</p>
            </div>
          </div>
          <div className="flex items-center gap-3 flex-shrink-0">
            <span className="hidden sm:inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-amber-500/20 text-amber-300 text-xs font-bold">
              <FlaskConical className="w-3.5 h-3.5" /> SIMULATION
            </span>
            <Link to="/login" className="text-xs font-semibold text-slate-300 hover:text-white min-h-[44px] flex items-center">
              Operator sign-in
            </Link>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 py-4 sm:py-6 space-y-4 sm:space-y-6">
        {/* Simulation notice */}
        <div className="flex items-start gap-2 p-3 rounded-xl bg-amber-50 border border-amber-200 text-amber-800 text-xs sm:text-sm">
          <FlaskConical className="w-4 h-4 flex-shrink-0 mt-0.5" />
          <span>
            <strong>This is a simulation.</strong> No hardware is connected. Every reading is generated by a
            model of the SWAMPDS pipeline running in your browser, so the leak-detection logic can be demonstrated
            without the physical prototype.
          </span>
        </div>

        {/* Status */}
        <SystemStatusBanner systemStatus={sim.status} />
        {sim.status === 'leak' && (
          <div role="status" className="p-3 rounded-xl bg-red-50 border border-red-200 text-red-800 text-sm">
            <strong>Affected section:</strong>{' '}
            {sim.leakSegments.map((id) => SEGMENTS[id].label).join('  and  ')}
          </div>
        )}

        {/* Schematic */}
        <Card>
          <CardHeader title="Pipeline Schematic" icon={Workflow} iconColorClass="text-blue-500" />
          <PipelineSchematic sim={sim} config={config} relay={outputs.relay} horizontal={wide} />
        </Card>

        {/* Controls + readouts */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6 items-start">
          <ControlPanel twin={twin} />

          <div className="space-y-4 sm:space-y-6">
            <HardwarePanel outputs={outputs} soundOn={soundOn} onToggleSound={() => setSoundOn((v) => !v)} />
            <DetectionPanel sim={sim} config={config} />
          </div>

          <div className="space-y-4 sm:space-y-6">
            <FlowChart data={chartData} animate={false} />
            <EventLog events={sim.events} startedAt={startedAt} />
            <Card>
              <CardHeader title="Demo guide" icon={Lightbulb} iconColorClass="text-amber-500" />
              <ol className="list-decimal pl-5 space-y-1.5 text-xs sm:text-sm text-slate-600 leading-snug">
                {DEMO_STEPS.map((s) => <li key={s}>{s}</li>)}
              </ol>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
}
